# Generated by Django 4.2.4 on 2023-09-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("Rooms & Apartment", "Rooms & Apartment"),
                            ("Food & Restaurant/Dining", "Food & Restaurant/dining"),
                            ("Concierges", "Concierges"),
                            ("Housekeeping", "Housekeeping"),
                            ("Spa & Fitness", "Spa & Fitness"),
                            ("Gym & Yoga", "Gym & Yoga"),
                            ("Event & Party", "Event & Party"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "service_logo",
                    models.ImageField(blank=True, null=True, upload_to="service_logo/"),
                ),
                (
                    "service_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_image/"
                    ),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
