# Generated by Django 4.2.4 on 2023-08-25 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("Executive/management", "Executive/management"),
                            ("Front Desk", "Front Desk"),
                            ("House Keeping", "House Keeping"),
                            ("Customer Care", "Customer Care"),
                            ("Food & Beverages", "Food & Beverages"),
                            ("Sales & Marketing", "Sales & Marketing"),
                            ("Human Resources", "Human Resources"),
                            ("Maintenance", "Maintenance"),
                            ("Security", "Security"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "service_logo",
                    models.ImageField(blank=True, null=True, upload_to="service_logo/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "hod",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
