# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("Rooms & Apartment", "Rooms & Apartment"),
                    ("Food & Restaurant/Dining", "Food & Restaurant/dining"),
                    ("Concierges", "Concierges"),
                    ("Housekeeping", "Housekeeping"),
                    ("Spa & Fitness", "Spa & Fitness"),
                    ("Gym & Yoga", "Gym & Yoga"),
                    ("Event & Party", "Event & Party"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
