# Generated by Django 4.2.4 on 2023-09-08 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicesApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingService",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("price", models.BigIntegerField(blank=True, null=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("reserved_date", models.DateField(blank=True, null=True)),
                ("reserved_time", models.TimeField(blank=True, null=True)),
                (
                    "reservation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=70,
                        null=True,
                    ),
                ),
                ("Total_no_Of_Guest", models.BigIntegerField(blank=True, null=True)),
                (
                    "special_request",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("payment", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesApp.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
