# Generated by Django 4.2.4 on 2023-09-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0002_bookingservice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingservice",
            old_name="Total_no_Of_Guest",
            new_name="No_Of_Guest",
        ),
    ]
