# Generated by Django 4.2.4 on 2023-08-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0002_alter_service_service_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service", old_name="hod", new_name="manager",
        ),
    ]
