# Generated by Django 4.2.4 on 2023-09-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicesApp", "0003_rename_total_no_of_guest_bookingservice_no_of_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="front_desk_receptionist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="front_desk_receptionist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="general_manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
