# Generated by Django 4.2.4 on 2023-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0003_rename_hod_service_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "room_name",
                    models.CharField(
                        choices=[
                            ("Rooms & Apartment", "Rooms & Apartment"),
                            ("Food & Restaurant/Dining", "Food & Restaurant/dining"),
                            ("Concierges", "Concierges"),
                            ("Housekeeping", "Housekeeping"),
                            ("Spa & Fitness", "Spa & Fitness"),
                            ("Gym & Yoga", "Gym & Yoga"),
                            ("Event & Party", "Event & Party"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "room_image",
                    models.ImageField(blank=True, null=True, upload_to="room_image/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
