# Generated by Django 4.2.4 on 2023-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0004_bookingservice_front_desk_receptionist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("Restaurant & Dining", "Restaurant & Dining"),
                    ("Concierges", "Concierges"),
                    ("Housekeeping", "Housekeeping"),
                    ("Spa & Fitness", "Spa & Fitness"),
                    ("Gym & Yoga", "Gym & Yoga"),
                    ("Event & Party", "Event & Party"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
