# Generated by Django 4.2.4 on 2023-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0004_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
