# Generated by Django 4.2.4 on 2023-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=70, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "room_image",
                    models.ImageField(blank=True, null=True, upload_to="room_image/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
