# Generated by Django 4.2.4 on 2023-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("General Manager", "General Manager"),
                    ("Human Resourses Manager", "Human Resourses Manager"),
                    ("Sales Manager", "Sales Manager"),
                    ("Front-Desk Receptionist", "Front-Desk Receptionist"),
                    ("House Keeper", "House Keeper"),
                    ("Concierges", "Concierges"),
                    ("Bartender", "Bartender"),
                    ("Server", "Server"),
                    ("Chef", "Chef"),
                    ("Sous Chef", "Sous Chef"),
                    ("Security", "Security"),
                    ("Maintenace Technician", "Maintenace Technician"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
