# Generated by Django 4.2.4 on 2023-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0002_alter_profile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Executive/management", "Executive/management"),
                    ("Front Desk", "Front Desk"),
                    ("House Keeping", "House Keeping"),
                    ("Customer Care", "Customer Care"),
                    ("Food & Beverages", "Food & Beverages"),
                    ("Sales & Marketing", "Sales & Marketing"),
                    ("Human Resources", "Human Resources"),
                    ("Maintenance", "Maintenance"),
                    ("Security", "Security"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
