# Generated by Django 4.2.4 on 2023-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0004_profile_occcupation_alter_profile_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="occcupation", new_name="occupation",
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default=None, max_length=50, null=True, unique=True
            ),
        ),
    ]
