# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0005_rename_occcupation_profile_occupation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Executive/management ", "Executive/management "),
                    ("Human Resources", "Human Resources"),
                    ("Customer Care", "Customer Care"),
                    ("Front Desk", "Front Desk"),
                    ("House Keeping", "House Keeping"),
                    ("Food & Beverages", "Food & Beverages"),
                    ("Sales & Marketing", "Sales & Marketing"),
                    ("Spa & Fitness", "Spa & Fitness"),
                    ("Gym & Yoga", "Gym & Yoga"),
                    ("Event & Party", "Event & Party"),
                    ("Maintenance", "Maintenance"),
                    ("Security", "Security"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
