# Generated by Django 4.2.4 on 2023-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0006_alter_profile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Executive/management ", "Executive/management "),
                    ("Human Resources", "Human Resources"),
                    ("Customer Care", "Customer Care"),
                    ("Front Desk", "Front Desk"),
                    ("House Keeping", "House Keeping"),
                    ("Rooms & Apartment", "ROoms & Apartment"),
                    ("Food & Beverages", "Food & Beverages"),
                    ("Sales & Marketing", "Sales & Marketing"),
                    ("Spa & Fitness", "Spa & Fitness"),
                    ("Gym & Yoga", "Gym & Yoga"),
                    ("Event & Party", "Event & Party"),
                    ("Maintenance", "Maintenance"),
                    ("Security", "Security"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("General Manager", "General Manager"),
                    ("Manager", "Manager"),
                    ("Sales Manager", "Sales Manager"),
                    ("Front-Desk Receptionist", "Front-Desk Receptionist"),
                    ("House Keeper", "House Keeper"),
                    ("Concierges", "Concierges"),
                    ("Bartender", "Bartender"),
                    ("Server", "Server"),
                    ("Chef", "Chef"),
                    ("Sous Chef", "Sous Chef"),
                    ("Security", "Security"),
                    ("Maintenace Technician", "Maintenace Technician"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
